version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "cargo"
    directory: "/builder"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "gomod"
    directory: "/builder-controller"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "gomod"
    directory: "/plugin"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
