name: Builder CI
on: 
  push:
    branches:    
      - 'master'
    paths:
      - 'builder/**'
      - '!builder/README.md'
      - '!builder/.gitignore'
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: redxiiikk/k8s-faas-builder
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./builder
          push: true
          tags: redxiiikk/k8s-faas-builder:v${{github.run_number}},redxiiikk/k8s-faas-builder:latest
          labels: ${{ steps.meta.outputs.labels }}
