name: CI
on: [ push, workflow_dispatch ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Formatting
        run: |
          gofmt -s -w .
      - name: Commit
        run: |
          if [ -z "$(git status --porcelain)" ]
          then
              echo "nothing to update."
          else
              git config --global user.name 'redxiiikk[action bot]'
              git config --global user.email '72877527+redxiiikk@users.noreply.github.com'
              git commit -am "style: automatic formatting by action"
              git push
          fi
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Test
        run: go test ./...
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o out/k8s-faas-builder-controller
      - uses: actions/upload-artifact@v2
        with:
          name: k8s-faas-builder-controller
          path: ${{ github.workspace }}/out/k8s-faas-builder-controller
          retention-days: 1
