name: Code Style Format
on: 
  push:
    paths:
      - '**.go'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Formatting
        run: |
          gofmt -s -w .
      - name: Commit
        run: |
          if [ -z "$(git status --porcelain)" ]
          then
              echo "code style is googd, nothing to update."
          else
              git config --global user.name 'redxiiikk[action bot]'
              git config --global user.email '72877527+redxiiikk@users.noreply.github.com'
              git commit -am "style: automatic formatting by action"
              git push
          fi
